version: '3.5'

networks:
  backend:
    name: backend
    driver: bridge
  nginx-proxy:
    external:
      name: nginx-proxy

services:
  mongo:
    networks:
      - nginx-proxy
      - backend
    restart: always
    image: dockerkleon/pkuweb:mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=tCaJXhP77xdKR4Y7
      - MONGO_INITDB_DATABASE=nx_zhiyuan
    volumes:
      - "./mongodb/:/data/db/"
      - "./data/db/:/init/"
    ports:
      - "27017:27017"

  frontend:
    networks:
      - nginx-proxy
    restart: always
    image: dockerkleon/pkuweb:frontend
    environment:
      - VIRTUAL_HOST=www.pkuzhiyuan.com
      - LETSENCRYPT_HOST=www.pkuzhiyuan.com
      - LETSENCRYPT_EMAIL=dingli.cm@gmail.com
      - NODE_ENV=production
      - VUE_APP_API_SERVER_URL=api.pkuzhiyuan.com
      - BASE_URL=www.pkuzhiyuan.com

  backend:
    networks:
      - nginx-proxy
      - backend
    restart: always
    image: dockerkleon/pkuweb:backend
    environment:
      - VIRTUAL_HOST=api.pkuzhiyuan.com
      - LETSENCRYPT_HOST=api.pkuzhiyuan.com
      - LETSENCRYPT_EMAIL=dingli.cm@gmail.com
      - NODE_ENV=production

  data_backend:
    networks:
      - backend
    restart: always
    image: dockerkleon/pkuweb:data_backend
    environment:
      - API_ENV=production

  mongo-express:
    networks:
      - nginx-proxy
      - backend
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=pku2020
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=tCaJXhP77xdKR4Y7
      - VIRTUAL_HOST=mongo.pkuzhiyuan.com
      - LETSENCRYPT_HOST=mongo.pkuzhiyuan.com
      - LETSENCRYPT_EMAIL=dingli.cm@gmail.com
