name: docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mongo
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dockerkleon/pkuweb
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: mongo
        tags: "mongo" 
    - name: frontend
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dockerkleon/pkuweb
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: frontend
        tags: "frontend"
    - name: backend
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dockerkleon/pkuweb
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: backend
        tags: "backend"
    - name: r_env
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dockerkleon/pkuweb
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: data_backend
        dockerfile: env.Dockerfile
        tags: "r_env"
    - name: data_backend
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dockerkleon/pkuweb
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: data_backend
        tags: "data_backend" 
